print('------ПОПУГАЙ------')
print('Введите первое слово: ', end='')
first_name = input()
print('Введите второе слово: ', end='')
second_name = input()
print('Введите третье слово: ', end='')
third_name = input()
print(third_name)
print(second_name)
print(first_name)