print('------ГОРОСКОП------')
print('Ваше имя: ', end='')
name = input()
print('Ваша фамилия: ', end='')
surname = input()
print('Ваше любимое животное: ', end='')
animal = input()
print('Ваш знак зодиака: ', end='')
zodiac_sign = input()
print('Индивидуальный гороскоп для пользователя', name, surname)
print('Кем вы были в прошлой жизни:', animal)
print('Ваш знак зодиака -', zodiac_sign, ', поэтому вы - тонко чувствующая натура.')
